# Global options:

[mypy]
python_version = 3.13
warn_return_any = True
warn_unused_configs = True
warn_no_return = True
warn_unused_ignores = True
warn_unreachable = True
warn_redundant_casts = True
no_implicit_optional = True
strict_optional = True
allow_redefinition = False
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
disallow_subclassing_any = True
pretty = True


# Per-module options:
# https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
[mypy-prometheus_flask_exporter.*]
ignore_missing_imports = True
